print("2")
print(2)
print(0x123)
print(3e8)
print(6.62607e-34)
print(0.000000000001)
print("Eu gosto \"Monty Python\"")
print('Eu gosto "Monty Python"')
print('I\'m Monty Python')
print(True > False)
print(True < False)
print('"Eu sou"')
print('""aprendizado""')
print('"""Python"""')
print()
print("\"Eu sou\"\n\"\"aprendizado\"\"\n\"\"\"Python\"\"\"")